export const keys = [
  { key: "Delete", display: "AC" },
  { key: "(", display: "(" },
  { key: ")", display: ")" },
  { key: "^", display: "^" },
  { key: "7", display: "7" },
  { key: "8", display: "8" },
  { key: "9", display: "9" },
  { key: "/", display: "÷" },
  { key: "4", display: "4" },
  { key: "5", display: "5" },
  { key: "6", display: "6" },
  { key: "*", display: "×" },
  { key: "1", display: "1" },
  { key: "2", display: "2" },
  { key: "3", display: "3" },
  { key: "-", display: "−" },
  { key: "0", display: "0" },
  { key: ".", display: "." },
  { key: "Enter", display: "=" },
  { key: "+", display: "+" }
]
